server:
  port: 8001

spring:
  application:
    name: ec
  cloud:
    config:
      name: test
      profile: dev
     # uri: http://localhost:8000/
      label: master
      discovery:
        enabled:  true
        serviceId: es



eureka:
  client:
    serviceUrl:
      #eureka生成服务器
      defaultZone: http://localhost:8000/eureka/
