eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8300
spring:
  application:
    name: zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: rb
    api-b:
      path: /api-b/**
      serviceId: feign