server:
  port: 8000

#ͨ通过registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: es
  cloud:
    config:
      server:
        git:
          uri: https://github.com/davidway/springcloud-learning.git  # 配置git仓库的地址
          search-paths: repo  # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 249261450@qq.com # git仓库的账号
          password: zhuweiqiang1130 # git仓库的密码
